lab4/Khalabarchuk_Project/app/posts/forms.py
from flask_login import current_user
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from flask_wtf.form import _Auto
from wtforms import StringField, SubmitField, TextAreaField, BooleanField, SelectField, SelectMultipleField
from wtforms.validators import DataRequired, Length, ValidationError
from wtforms.widgets import CheckboxInput, ListWidget

from .entitys import PostType, Post, Category, Tag


class CreateEditCategory(FlaskForm):
    name = StringField("name", validators=[
        DataRequired("This field is required"),
        Length(4, 40, "The length must be greater than 4 and less than 90")
    ])
    submit = SubmitField("Save")

    def validate_name(self, field):
        if Category.query.filter(Category.name.ilike(field.data)).first():
            raise ValidationError("The category with this name is already busy")


class SearchPostForm(FlaskForm):
    category = SelectField("Category", default="ANY")
    submit = SubmitField("Search")

    def __init__(self, *args, **kwargs):
        super(SearchPostForm, self).__init__(*args, **kwargs)
        self.category.choices = [(c.id, c.name) for c in Category.query.all()] + [("ANY", "Any")]


class CreateEditPostForm(FlaskForm):
    title = StringField("Title", validators=[
        DataRequired("This field is required"),
        Length(4, 90, "The length must be greater than 4 and less than 90")
    ])
    text = TextAreaField("Post text", validators=[
        DataRequired("This field is required"),
        Length(0, 2000, "The length must be greater than 0 and less than 2000")
    ])
    image = FileField("Post picture", validators=[
        FileAllowed(["jpg", "png", "jfif", "gif"])
    ])
    type = SelectField("Type", choices=[(c.name, c.value) for c in PostType])
    category = SelectField("Category", choices=[(c.id, c.name) for c in Category.query.all()])
    tags = SelectMultipleField("Tags", choices=[(t.name, t.name) for t in Tag.query.all()],
                               option_widget=CheckboxInput(), widget=ListWidget(prefix_label=False))
    enable = BooleanField("Published")
    submit = SubmitField("Save")

    def __init__(self, *args, **kwargs):
        super(CreateEditPostForm, self).__init__(*args, **kwargs)
        self.category.choices = [(c.id, c.name) for c in Category.query.all()]
        self.tags.choices = [(t.name, t.name) for t in Tag.query.all()]

    def build_post(self) -> Post:
        post = Post(
            title=self.title.data,
            text=self.text.data,
            type=self.type.data,
            enable=self.enable.data,
            category_id=self.category.data,
            tags=[t for t in Tag.query.filter(Tag.name.in_(self.tags.data)).all()],
            user_id=current_user.id
        )

        post.set_post_image(self.image.data)

        return post

    def build_edit_form(self, post: Post):
        self.title.data = post.title
        self.type.default = post.type.name
        self.text.data = post.text
        self.enable.data = post.enable
        self.category.data = post.category
        self.tags.data = [t.name for t in post.tags]

lab4/Khalabarchuk_Project/app/posts/__init__.py
from flask import Blueprint

posts_bp = Blueprint("posts", __name__, template_folder="templates/posts", static_folder="static")

from . import views

lab4/Khalabarchuk_Project/app/posts/views.py
from flask import redirect, url_for, flash, request
from flask_login import login_required
from sqlalchemy import desc

from .forms import *
from .entitys import *

from ..common_logic import base_render

from . import posts_bp


@posts_bp.route("/", methods=["GET", "POST"])
@login_required
def all_posts():
    form = SearchPostForm()
    page = request.args.get("page", 1, type=int)
    per_page = request.args.get("per_page", config.POSTS_MAX_PER_PAGE, type=int)
    category = request.args.get("category", "ANY") if request.method == "GET" else form.category.data
    posts = Post.query

    if (form.validate_on_submit() or request.method == "GET") and category != "ANY":
        form.category.data = category
        posts = posts.filter(Post.category.has(id=form.category.data))

    posts = posts.order_by(desc(Post.created)).paginate(page=page, per_page=per_page)

    return base_render("all-posts.html", posts=posts, form=form)


@posts_bp.route("/<int:id>")
@login_required
def get_post(id):
    post = Post.query.get(id)

    if not post:
        flash("Post not found", "warning")
        return redirect(url_for("posts.all_posts"))

    return base_render("post.html", post=post)


@posts_bp.route("/create", methods=["GET", "POST"])
@login_required
def create_post():
    form = CreateEditPostForm()

    if form.validate_on_submit():
        post = form.build_post()
        db.session.add(post)
        db.session.commit()

        return redirect(url_for("posts.get_post", id=post.id))

    flash("Post successfully established", "success")
    return base_render("edit-post.html",
                       form=form,
                       form_title="Create post❤️‍🩹",
                       form_action=url_for("posts.create_post"))


@posts_bp.route("/<int:id>/update", methods=["GET", "POST"])
@login_required
def update_post(id):
    post: Post = Post.query.get(id)

    if not post:
        flash("Post not found", "warning")
        return redirect(url_for("posts.all_posts"))

    form = CreateEditPostForm()

    if form.validate_on_submit():
        post.update(form)

        db.session.commit()

        flash("You have successfully update a post", "success")
        return redirect(url_for("posts.get_post", id=post.id))
    else:
        form.build_edit_form(post)

    return base_render("edit-post.html",
                       form=form,
                       form_title="Edit post‍🐍",
                       form_action=url_for("posts.update_post", id=post.id))


@posts_bp.route("/<int:id>/delete", methods=["GET"])
@login_required
def delete_post(id):
    post: Post = db.get_or_404(Post, id)

    if post.user_id != current_user.id:
        flash("You must be the owner of the post to delete it", "danger")
        return redirect(url_for("posts.get_post", id=id))

    db.session.delete(post)
    db.session.commit()

    flash("Post successfully deleted", "success")
    return redirect(url_for("posts.all_posts"))


@posts_bp.route("/categories")
@login_required
def categories():
    categories_with_forms = [{"id": c.id, "form": CreateEditCategory(name=c.name)} for c in Category.query.all()]
    form = CreateEditCategory()
    return base_render("all-categories.html", categories=categories_with_forms, form=form)


@posts_bp.route("/category/<int:id>/update", methods=["POST"])
def category_update(id):
    form = CreateEditCategory()

    if form.validate_on_submit():
        category = db.get_or_404(Category, id)

        category.name = form.name.data
        db.session.commit()
        flash("You have successfully update a category", "success")
    else:
        flash("A category with this name already exists", "danger")

    return redirect(url_for("posts.categories"))


@posts_bp.route("/category/<int:id>/delete", methods=["GET"])
def category_delete(id):
    db.session.delete(db.get_or_404(Category, id))
    db.session.commit()

    flash("Category successfully deleted", "success")
    return redirect(url_for("posts.categories"))


@posts_bp.route("/category/create", methods=["POST"])
def category_create():
    form = CreateEditCategory()

    if form.validate_on_submit():
        category = Category(name=form.name.data)

        db.session.add(category)
        db.session.commit()
        flash("Category successfully established", "success")
    else:
        flash("A category with this name already exists", "danger")

    return redirect(url_for("posts.categories"))

lab4/Khalabarchuk_Project/app/posts/templates/posts/all-categories.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('posts.static', filename='css/all-categories.css') }}">
{% endblock %}

{% block content %}
    {% from "render-filed.html" import render_field %}

    <div class="main-wrapper">
        <div class="main">
            <h3>Categories🧠</h3>
            <main class="categories-wrapper">
                {% for category in categories %}
                    <form action="{{ url_for("posts.category_update", id=category.id) }}"
                          method="post"
                          class="category-form"
                          novalidate
                    >
                        {{ category.form.csrf_token }}
                        <div> {{ render_field(category.form.name) }} </div>
                        <div class="d-flex justify-content-center align-items-center">
                            {{ category.form.submit(class="btn btn-primary") }}
                        </div>
                        <a href="{{ url_for("posts.category_delete", id=category.id) }}">
                            <button type="button" class="btn btn-danger">
                                Delete
                            </button>
                        </a>
                    </form>
                {% else %}
                    <p>Categories not found</p>
                {% endfor %}
            </main>
        </div>
        <div class="main">
            <h3>Create category🦜</h3>
            <main class="categories-wrapper">
                <form action="{{ url_for("posts.category_create") }}"
                      method="post"
                      class=""
                      novalidate
                >
                    {{ form.csrf_token }}
                    <div> {{ render_field(form.name) }} </div>
                    <div class="d-flex justify-content-center align-items-center">
                        {{ form.submit(class="default-submit") }}
                    </div>
                </form>
            </main>
        </div>
    </div>
{% endblock %}

lab4/Khalabarchuk_Project/app/posts/templates/posts/all-posts.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('posts.static', filename='css/all-posts.css') }}">
{% endblock %}

{% block content %}
    {% from "render-filed.html" import render_field %}

    <div class="main-wrapper">
        <main class="main">
            <div class="posts-header">
                <h3>🕊️Posts:</h3>

                {% if form %}
                    <form action="{{ url_for("posts.all_posts") }}"
                          method="post"
                          class="search-form"
                          novalidate
                    >
                        {{ form.csrf_token }}
                        <div> {{ render_field(form.category) }} </div>
                        <div class="d-flex justify-content-center align-items-center">
                            {{ form.submit(class="default-submit") }}
                        </div>
                    </form>
                {% endif %}

                <a href="{{ url_for("posts.create_post") }}"
                   class="btn btn-success"
                >
                    Create post
                </a>
            </div>
            <div class="posts">
                {% for post in posts.items %}
                    <div class="post">
                        <div class="d-flex flex-direction-row">
                            <a class="post-title" href="{{ url_for("posts.get_post", id=post.id) }}">
                                <div class="post-image"
                                     style="background-image:
                                             url('{{ url_for('static', filename='post-images/' + post.image) }}')"
                                ></div>
                            </a>

                            <a class="post-title"
                               href="{{ url_for("posts.get_post", id=post.id) }}">{{ post.title }}</a>
                        </div>
                        <div>
                            <a class="post-title"
                               href="{{ url_for("posts.get_post", id=post.id) }}">
                                <button type="button" class="btn btn-primary">
                                    Show
                                </button>
                            </a>
                        </div>
                    </div>
                {% else %}
                    <p>No posts were found</p>
                {% endfor %}
            </div>
        </main>

        <nav aria-label="...">
            <ul class="pagination">
                <li class="page-item {% if not posts.has_prev %}disabled{% endif %}">
                    <a class="page-link"
                       href="{{ url_for(".all_posts", page=posts.prev_num, category=form.category.data) }}"
                       tabindex="-1">Previous</a>
                </li>

                {% for page in posts.iter_pages(left_edge=2, left_current=1, right_current=1, right_edge=2) %}
                    <li class="page-item {% if page == posts.page %}active{% endif %}">
                        <a class="page-link"
                           href="{{ url_for("posts.all_posts", page=page, category=form.category.data) }}">
                            {{ page or "..." }}
                        </a>
                    </li>
                {% endfor %}

                <li class="page-item {% if not posts.has_next %}disabled{% endif %}">
                    <a class="page-link"
                       href="{{ url_for(".all_posts", page=posts.next_num, category=form.category.data) }}">Next</a>
                </li>
            </ul>
        </nav>
    </div>
{% endblock %}

lab4/Khalabarchuk_Project/app/posts/templates/posts/edit-post.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('posts.static', filename='css/edit-post.css') }}">
{% endblock %}

{% block content %}
    {% from "render-filed.html" import render_field %}

    <div class="main-wrapper">
        <main class="main">
            <form action="{{ form_action }}"
                  method="post"
                  class="post-form"
                  novalidate
                  enctype="multipart/form-data"
            >
                {{ form.csrf_token }}
                <div class="form-header">
                    <p class="form-title">{{ form_title }}</p>
                </div>
                <div> {{ render_field(form.title) }} </div>
                <div> {{ render_field(form.text, style="z-index: 1000;") }} </div>
                <div> {{ render_field(form.image) }} </div>
                <div> {{ render_field(form.type) }} </div>
                <div> {{ render_field(form.category) }} </div>
                <div> {{ render_field(form.tags, class="tags", multiple=True) }} </div>
                <div class="checkbox"> {{ render_field(form.enable) }} </div>
                <div class="d-flex justify-content-center align-items-center">
                    {{ form.submit(class="default-submit") }}
                </div>
            </form>
        </main>
    </div>
{% endblock %}

lab4/Khalabarchuk_Project/app/posts/templates/posts/post.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('posts.static', filename='css/post.css') }}">
{% endblock %}

{% block content %}
    {% from "render-filed.html" import render_field %}

    <div class="main-wrapper">
        <main class="main">
            <div class="post-wrapper">
                <div class="post-title-wrapper">
                    <div class="post-image"
                         style="background-image:
                                 url('{{ url_for('static', filename='post-images/' + post.image) }}')"
                    ></div>
                    <div class="post-title">
                        {{ post.title }}
                    </div>

                    {% if current_user.id == post.user_id %}
                        <div class="post-buttons">
                            <a href="{{ url_for("posts.update_post", id=post.id) }}">
                                <button type="button" class="btn btn-primary">
                                    Edit
                                </button>
                            </a>
                            <a href="{{ url_for("posts.delete_post", id=post.id) }}">
                                <button type="button" class="btn btn-danger">
                                    Delete
                                </button>
                            </a>
                        </div>
                    {% endif %}
                </div>
                <div class="post-body">
                    <div class="post-header">
                        <div class="post-details">
                            <div class="post-type {{ post.type.name }}">
                            {{ post.type.name }}
                        </div>
                        <div class="post-category">
                            {{ post.category.name }}
                        </div>
                        </div>
                        <div class="post-create-time">
                            {{ post.created }}
                        </div>
                    </div>
                    <div class="post-main">
                        {{ post.text }}
                    </div>
                    <div class="post-tags">
                        {% for tag in post.tags %}
                            <div class="post-tag">{{ tag.name }}</div>
                        {% else %}
                            <p>The post does not contain tags</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </main>
    </div>
{% endblock %}