lab4/Khalabarchuk_Project/app/todo/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class ToDoForm(FlaskForm):
    title = StringField("", validators=[DataRequired(message="This field is required.")])
    submit = SubmitField("Save")

lab4/Khalabarchuk_Project/app/todo/__init__.py
from flask import Blueprint

todo_bp = Blueprint("todo", __name__, template_folder="templates/todo", static_folder="static")

from . import views

lab4/Khalabarchuk_Project/app/todo/views.py
from flask import redirect, url_for, flash
from flask_login import login_required

from app import db
from ..common_logic import base_render
from .forms import ToDoForm
from .entitys import ToDo

from . import todo_bp


@todo_bp.route('/todo', methods=["GET"])
@login_required
def todo_page():
    return base_render("todo-page.html", todo_list=ToDo.query.all(), todo_form=ToDoForm())


@todo_bp.route("/todo", methods=["POST"])
@login_required
def add_todo():
    todo_form = ToDoForm()
    if todo_form.validate_on_submit():
        new_todo = ToDo(title=todo_form.title.data, completed=False, status=ToDo.Status.IN_PROGRESS)
        db.session.add(new_todo)
        db.session.commit()

        flash('Todo added successfully', 'success')

    return redirect(url_for("todo.todo_page"))


@todo_bp.route("/todo/<string:id>")
@login_required
def delete_todo(id: str):
    todo = db.get_or_404(ToDo, id)
    db.session.delete(todo)
    db.session.commit()
    flash('Todo deleted successfully', 'success')

    return redirect(url_for("todo.todo_page"))


@todo_bp.route("/todo/<string:id>/update")
@login_required
def update_todo(id: str):
    todo = db.get_or_404(ToDo, id)
    todo.complete()

    db.session.commit()
    flash('Todo updated successfully', 'success')

    return redirect(url_for("todo.todo_page"))

lab4/Khalabarchuk_Project/app/todo/templates/todo/todo-page.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('todo.static', filename='css/todo-page.css') }}">
{% endblock %}

{% set status_style_class = {
"COMPLETED": "alert-success",
"IN_PROGRESS": "alert-secondary"
} %}

{% from "render-filed.html" import render_field %}

{% block content %}

    <div class="main-wrapper">
        <main class="main container w-50">
            <div class="row">
                <h3>Python Flask Simple To Do - SQLAlchemy</h3>
            </div>
            <div class="row container">
                <form
                        class="row todo-add-part d-flex flex-row align-items-center"
                        action="{{ url_for("todo.add_todo") }}"
                        METHOD="post"
                        novalidate
                >
                    {{ todo_form.csrf_token }}
                    {{ render_field(todo_form.title, class="default-input", placeholder="Enter task title here") }}
                    {{ todo_form.submit(class="default-submit w-auto mx-4") }}
                </form>
                <div class="row todo-table">
                    <table>
                        <thead>
                        <tr>
                            <th scope="col">No.</th>
                            <th scope="col">Todo item</th>
                            <th scope="col">Status</th>
                            <th scope="col">Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for todo in todo_list %}
                            <tr>
                                <th scope="row">{{ todo.id }}</th>
                                <td>{{ todo.title }}</td>
                                <td>
                                    <div class="alert {{ status_style_class[todo.status] }}" role="alert">
                                        {{ todo.status }}
                                    </div>
                                </td>
                                <td>
                                    <a href="{{ url_for("todo.update_todo", id=todo.id) }}" class="btn btn-success">Update</a>
                                    <a href="{{ url_for("todo.delete_todo", id=todo.id) }}" class="btn btn-danger ms-1">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </main>
    </div>

{% endblock %}