lab4/Khalabarchuk_Project/app/common/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class CommentForm(FlaskForm):
    comment = StringField("", validators=[DataRequired(message="This field is required.")])
    submit = SubmitField("Comment")

lab4/Khalabarchuk_Project/app/common/__init__.py
from flask import Blueprint


common_bp = Blueprint("common", __name__, template_folder="templates/common", static_folder="static")

from . import views

lab4/Khalabarchuk_Project/app/common/views.py
from datetime import datetime

from flask import request, flash, redirect, url_for
from flask_login import login_required, current_user

# from ..authentication.forms import ChangePasswordForm
from app import db

from ..common_logic import base_render

from . import common_bp
from .entitys import Comment
from .forms import CommentForm

PROJECTS_LIST = [{
    "photo_url": "projectNMWS.png",
    "name": "NM-WebSockets",
    "project_url": "https://github.com/JJerome-NM/NM-WebSockets"
}, {
    "photo_url": "projectCodenames.png",
    "name": "CodeNames",
    "project_url": "https://github.com/JJerome-NM/CodeNames"
}, {
    "photo_url": "projectWSHelper.png",
    "name": "WebSocketHelper",
    "project_url": "https://github.com/JJerome-NM/WebSocketHelper"
}]

CONTACTS = [{
    "type": "EMAIL",
    "contact_name": "Gmail",
    "name": "Mykhailo Khalabarchuk",
    "link": "mykhailo.khalabarchuk.21@pnu.edu.ua",
    "title": "JJerome-NM"
}, {
    "type": "DEFAULT",
    "contact_name": "Linkedin",
    "name": "Mykhailo Khalabarchuk",
    "link": "https://www.linkedin.com/in/mykhailo-khalabarchuk-26376528b/",
    "title": "Mykhailo Khalabarchuk"
}, {
    "type": "DEFAULT",
    "contact_name": "Github",
    "name": "Михайло Халабарчук",
    "link": "https://github.com/JJerome-NM",
    "title": "Михайло Халабарчук"
}]

SKILLS_LIST = list([{
    "name": "Java Core",
    "title": "Java Core, often referred to as 'Core Java,' is a term used to describe the fundamental and essential components of the Java programming language. It encompasses the basic concepts, libraries, and features that are integral to Java development. Core Java forms the foundation upon which more advanced Java technologies and frameworks are built.",
}, {
    "name": "Java Spring",
    "title": "Java Spring, often referred to simply as Spring, is a popular and powerful framework for building Java-based enterprise applications. It provides a comprehensive infrastructure for developing robust and maintainable applications, with a focus on modularity, scalability, and ease of testing. Spring is known for simplifying many aspects of Java development and has become a cornerstone of the Java ecosystem for building web, cloud, and enterprise applications.",
}, {
    "name": "Spring Data",
    "title": "Spring Data is a part of the larger Spring Framework ecosystem that simplifies data access and persistence in Java applications. It provides a unified and consistent way to interact with various data sources, such as relational databases, NoSQL databases, and other data storage technologies. Spring Data aims to reduce the boilerplate code typically required for data access and to improve developer productivity.",
}, {
    "name": "Spring Security",
    "title": "Spring Security is a powerful and highly customizable security framework provided by the Spring Framework for building secure Java-based applications. It focuses on authentication, authorization, and protection against common security vulnerabilities. Spring Security is widely used in web applications, microservices, and other Java-based systems to ensure the security of the application and its resources.",
}, {
    "name": "Python",
    "title": "Python is a high-level, versatile, and interpreted programming language that has gained tremendous popularity in the world of computer programming since its creation in the late 1980s. Here are some key aspects of Python as a skill:",
}, {
    "name": "WebSocket",
    "title": "WebSocket is a communication protocol that provides full-duplex, bidirectional communication channels over a single TCP connection. It is designed to be efficient and lightweight, making it a suitable choice for real-time web applications. WebSocket allows for interactive and dynamic communication between a client (usually a web browser) and a server, enabling data to be transmitted in both directions without the need for the client to repeatedly request data",
}, {
    "name": "Rest",
    "title": "Rest is a fundamental skill that is crucial for maintaining physical and mental well-being. It refers to the act of taking a break or allowing oneself to relax and recuperate from physical, mental, or emotional exertion. Rest is essential for recharging and revitalizing the body and mind. Here are some key aspects of the skill of rest",
}])


@common_bp.route("/comments")
@login_required
def comments_page():
    return base_render("comments-page.html", comment_form=CommentForm(), comments=Comment.query.all())


@common_bp.route("/comments", methods=["POST"])
@login_required
def add_comment():
    comment_form = CommentForm()

    if comment_form.validate_on_submit():
        date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        new_comment = Comment(username=current_user.username, comment=comment_form.comment.data, date=date)
        db.session.add(new_comment)
        db.session.commit()

        flash('Comment added successfully', 'success')
    else:
        flash('Something went wrong while adding a comment', 'danger')

    return redirect(url_for("common.comments_page"))


@common_bp.route("/info")
@login_required
def info():
    return base_render("info.html", cookies=request.cookies.items())


@common_bp.route('/')
@common_bp.route('/portfolio')
def portfolio_main():
    return base_render("portfolio-main.html")


@common_bp.route('/projects')
def portfolio_projects():
    return base_render("portfolio-projects.html", projects_list=PROJECTS_LIST)


@common_bp.route('/contacts')
def portfolio_contacts():
    return base_render("portfolio-contacts.html", contacts=CONTACTS)


@common_bp.route('/skills')
@common_bp.route('/skills/<int:id>')
def portfolio_skills(id: int = None):
    if id is not None:
        return base_render("portfolio-skills.html", selected_skill=SKILLS_LIST[id])

    return base_render("portfolio-skills.html", all_skills_list=SKILLS_LIST)

lab4/Khalabarchuk_Project/app/common/templates/common/comments-page.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('common.static', filename='css/comments-page.css') }}">
{% endblock %}

{% from "render-filed.html" import render_field %}

{% block content %}

    <div class="main-wrapper">
        <main class="main container w-50">
            <form class="row todo-add-part d-flex flex-row align-items-center w-100"
                  action="{{ url_for("common.add_comment") }}"
                  METHOD="post"
                  novalidate
            >
                {{ comment_form.csrf_token }}
                {{ render_field(comment_form.comment, class="default-input", placeholder="Enter comment here") }}
                {{ comment_form.submit(class="default-submit w-auto mx-4") }}
            </form>

            <div class="container">
                Comments:
            </div>

            <div class="comments-block container d-flex justify-content-center flex-column align-items-center">
                {% for comment in comments %}

                    <div class="container comment-wrapper d-flex flex-column">
                        <div class="container d-flex flex-row justify-content-between">
                            <div class="username">{{ comment.username }}</div>
                            <div class="date">{{ comment.date }}</div>
                        </div>
                        <hr style="margin: 2px 0; ">
                        <div class="comment container">
                            {{ comment.comment }}
                        </div>
                    </div>

                {% endfor %}
            </div>

        </main>
    </div>
{% endblock %}

lab4/Khalabarchuk_Project/app/common/templates/common/info.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('common.static', filename='css/info.css') }}">
{% endblock %}

{% block content %}
    {% from "render-filed.html" import render_field %}

    <div class="main-wrapper">
        <main class="main">
            <div class="info-header">
                {% if current_user.is_authenticated %}
                    <h2>Hello my dear {{ current_user.username }}!</h2>
                {% else %}
                    <h2>Hello my dear user!</h2>
                {% endif %}
            </div>

            {% if current_user.is_authenticated %}
                <div class="info-logout">
                    <a class="default-submit" href="{{ url_for("auth.logout") }}">Logout</a>
                </div>
            {% endif %}

            <div class="info-main">
                <div class="add-remove-block">
                    <form class="form-block" action="{{ url_for("cookie.add_cookie") }}" method="post">
                        <div class="form-row">
                            <label for="cookie_key">
                                Key
                            </label>
                            <input class="default-input" type="text" id="cookie_key" name="cookie_key"
                                   placeholder="Enter cookie key">
                        </div>
                        <div class="form-row">
                            <label for="cookie_value">
                                Value
                            </label>
                            <input class="default-input" type="text" id="cookie_value" name="cookie_value"
                                   placeholder="Enter cookie value">
                        </div>
                        <div class="form-row">
                            <label for="expires_at">
                                Expire at
                            </label>
                            <input class="default-input" type="text" id="expires_at" name="expires_at"
                                   placeholder="Enter cookie expire at">
                        </div>

                        <button type="submit" class="default-submit">Add cookie</button>
                    </form>

                    <div class="form-block">
                        <h3>All your cookies</h3>
                        <table class="cookie-table">
                            <thead>
                            <tr>
                                <th scope="col">Key</th>
                                <th scope="col">Value</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for cookie_key, cookie_value in cookies %}
                                {% if cookie_key != "session" %}
                                    <tr>
                                        <td>{{ cookie_key }}</td>
                                        <td>{{ cookie_value }}</td>
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            </tbody>
                        </table>

                    </div>

                    <form class="form-block" action="{{ url_for("cookie.remove_cookie") }}" method="post">
                        <div class="form-row">
                            <label for="cookie_key">
                                Key
                            </label>
                            <input class="default-input" type="text" id="cookie_key" name="cookie_key"
                                   placeholder="Enter cookie key">
                        </div>
                        <div class="buttons-block">
                            <button type="submit" class="default-submit">Remove cookie</button>
                        </div>
                    </form>
                    <form action="{{ url_for("cookie.remove_cookie") }}" method="post" class="form-block">
                        <button type="submit" class="default-submit">Remove all cookie</button>
                    </form>

                    {% if change_password_from %}
                        <form class="form-block change-pass-form" action="{{ url_for("auth.change_password") }}"
                              method="post" novalidate>
                            {{ change_password_from.csrf_token }}
                            <div class="form-row form-input"> {{ render_field(change_password_from.old_password) }} </div>
                            <div class="form-row form-input"> {{ render_field(change_password_from.new_password) }} </div>
                            <div class="form-row form-submit"> {{ change_password_from.submit(class="default-submit") }} </div>
                        </form>
                    {% endif %}
                </div>
            </div>
        </main>
    </div>

{% endblock %}

lab4/Khalabarchuk_Project/app/common/templates/common/portfolio-contacts.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('common.static', filename='css/portfolio-contacts.css') }}">
{% endblock %}

{% block content %}
    <div class="main-wrapper">
        <main class="main">
            <div class="contacts-wrapper">
                <div class="contacts">
                    <div class="contacts-title">
                        <h3>You can contact me via:</h3>
                    </div>
                    <ul class="contacts-list">
                        {% if contacts %}
                            {% for contact in contacts %}
                                <li class="contact-wrapper">
                                    {% if contact.contact_icon_url %}
                                        <img class="contact-icon" src="{{ contact.contact_icon_url }}"
                                             alt="Contact icon">
                                    {% else %}
                                        <span class="contact-icon"></span>
                                    {% endif %}
                                    <div class="contact">
                                        <h4>{{ contact.contact_name }}:</h4>

                                        {% if contact.type == "DEFAULT" %}
                                            <a href="{{ contact.link }}">{{ contact.name }}</a>
                                        {% else %}
                                            <h4>{{ contact.name }}</h4>
                                            <h5>Link: {{ contact.link }}</h5>
                                        {% endif %}

                                    </div>
                                </li>
                            {% endfor %}
                        {% else %}
                            <li><h4>Контактів не знайдено</h4></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </main>
    </div>
{% endblock %}

lab4/Khalabarchuk_Project/app/common/templates/common/portfolio-main.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('common.static', filename='css/portfolio-main.css') }}">
{% endblock %}

{% block content %}
    <div class="main-wrapper bg-white-gradient">
        <main class="main">
            <div class="photo-wrapper">
                <img class="photo" alt="My coold photo" src="{{ url_for('static', filename='images/myPhoto.jfif') }}"/>
            </div>
            <div class="about-me-wrapper">
                <div class="title-wrapper">
                    <h2 class="title">Hello its me</h2>
                    <h3 class="some-about-me-text">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit.
                        A cupiditate, et exercitationem harum illum nisi provident.
                        Doloribus eum ipsum labore natus nisi porro possimus repudiandae sequi velit voluptatum.
                        Blanditiis, magnam!
                    </h3>
                </div>
                <a class="projects-button default-button" href="{{ url_for('common.portfolio_projects') }}">Projects</a>
            </div>
        </main>
    </div>

{% include "main-footer.html" %}
{% endblock %}

lab4/Khalabarchuk_Project/app/common/templates/common/portfolio-projects.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('common.static', filename='css/portfolio-projects.css') }}">
{% endblock %}

{% block content %}
    <div class="main-wrapper">
        <main class="main">
            {% if projects_list %}
                <ul class="projects-list">
                    {% for project in projects_list %}
                        <li class="project">
                            <img class="project-photo"
                                 src="{{ url_for('static', filename='images/' + project.photo_url) }}"
                                 alt="project icon"
                            >
                            <a href="{{ project.project_url }}">{{ project.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <h3 style="font-weight: 400; text-align: center">Список проектів порожній</h3>
            {% endif %}

        </main>
    </div>

{% endblock %}

lab4/Khalabarchuk_Project/app/common/templates/common/portfolio-skills.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('common.static', filename='css/portfolio-skills.css') }}">
{% endblock %}

{% block content %}
    <div class="main-wrapper">
        <main class="main">
            {% if all_skills_list %}
                <div class="skills-header">
                    <h1>My skills</h1>
                </div>
                <div class="skills-list">
                    {% for index, skill in all_skills_list|enumerate %}
                        <a class="skill" href="{{ url_for('common.portfolio_skills') }}/{{ index }}">{{ skill.name }}</a>
                    {% endfor %}
                </div>
            {% endif %}
            {% if selected_skill and not all_skills_list %}
                <h2>{{ selected_skill.name }}</h2>
                <h3>{{ selected_skill.title }}</h3>
            {% endif %}
        </main>
    </div>
{% endblock %}