lab4/Khalabarchuk_Project/app/authentication/forms.py
from flask_login import current_user
from flask_wtf.file import FileAllowed, FileField
from flask_wtf import FlaskForm
from wtforms import StringField, EmailField, PasswordField, SubmitField, TextAreaField, BooleanField
from wtforms.validators import DataRequired, Length, Regexp, ValidationError

from .entitys import AuthUser


class UserRegistrationBaseImplementationForm(FlaskForm):

    def validate_username(self, username):
        if current_user.is_authenticated and current_user.username == username.data:
            return

        if AuthUser.query.filter_by(username=username.data).first():
            raise ValidationError("Username is busy")

    def validate_email(self, email):
        if current_user.is_authenticated and current_user.email == email.data:
            return

        if AuthUser.query.filter_by(email=email.data).first():
            raise ValidationError("Email is busy")


class RegistrationForm(UserRegistrationBaseImplementationForm, FlaskForm):
    username = StringField('Username', validators=[
        DataRequired("This field is required"),
        Length(4, 30, "The length must be greater than 4 and less than 30"),
        Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, 'Nickname can include only letters, numbers, underscore and a dot')
    ])
    email = EmailField('Email(Login)', validators=[DataRequired("This field is required")])
    password = PasswordField('Password', validators=[
        DataRequired("This field is required"),
        Length(min=4, max=30, message="The length must be greater than 4 and less than 30")
    ])
    confirm_password = PasswordField('Confirm password', validators=[
        DataRequired("This field is required"),
        Length(min=4, max=30, message="The length must be greater than 4 and less than 30")
    ])
    submit = SubmitField("Sign-up")


class ChangeUserDetailsForm(UserRegistrationBaseImplementationForm, FlaskForm):
    username = StringField('Username', validators=[
        DataRequired("This field is required"),
        Length(4, 30, "The length must be greater than 4 and less than 30"),
        Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, 'Nickname can include only letters, numbers, underscore and a dot')
    ])
    email = EmailField('Email(Login)', validators=[DataRequired("This field is required")])
    avatar_image = FileField("User avatar", validators=[
        FileAllowed(["jpg", "png", "jfif", "gif"])
    ])
    about_me = TextAreaField(label="About me:", validators=[
        Length(min=0, max=500, message="The length must be less than 500 chars")
    ])
    new_password = PasswordField('New password', validators=[])
    confirm_password = PasswordField('Confirm new password', validators=[])
    old_password = PasswordField('Current password', validators=[
        DataRequired("To save changes, you need to enter the old password")
    ])
    submit = SubmitField("Save changes")

    def validate_new_password(self, password):
        if password.data and 4 > len(password.data) < 30:
            raise ValidationError("The length must be greater than 4 and less than 30")

    def validate_confirm_password(self, password):
        if password.data and 4 > len(password.data) < 30:
            raise ValidationError("The length must be greater than 4 and less than 30")

        if self.new_password.data and password.data != self.new_password.data:
            raise ValidationError("New password must be the identical to confirm password")

    def validate_old_password(self, old_pass):
        if old_pass.data and not current_user.verify_password(old_pass.data):
            raise ValidationError("The password you entered is not correct")

class LoginForm(FlaskForm):
    login = StringField('Login', validators=[DataRequired("This field is required")])
    password = PasswordField('Password', validators=[
        DataRequired("This field is required"),
        Length(min=4, max=30, message="The length must be greater than 3 and less than 30")
    ])
    remember = BooleanField('Remember')
    submit = SubmitField("Sign-in")


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('Old password', validators=[DataRequired("This field is required!")])
    new_password = PasswordField('New password', validators=[
        DataRequired("This field is required"),
        Length(min=4, max=10, message="The length must be greater than 3 and less than 10")
    ])
    submit = SubmitField("Change password")

lab4/Khalabarchuk_Project/app/authentication/__init__.py
from flask import Blueprint

auth_bp = Blueprint("auth", __name__, template_folder="templates/authentication", static_folder="static")

from . import views

lab4/Khalabarchuk_Project/app/authentication/views.py
from flask import redirect, url_for, flash, session, request
from flask_login import login_required, current_user, login_user, logout_user

from ..common_logic import base_render
from .. import db

from .forms import LoginForm, ChangePasswordForm, RegistrationForm, ChangeUserDetailsForm
from ..authentication.entitys import AuthUser

from . import auth_bp


@auth_bp.route("/users")
@login_required
def get_users():
    return base_render("all-users.html", users=AuthUser.query.all())


@auth_bp.route("/register", methods=["GET", "POST"])
def sign_up():
    if current_user.is_authenticated:
        return redirect(url_for("info"))

    reg_form = RegistrationForm()

    if reg_form.validate_on_submit():
        user = AuthUser(email=reg_form.email.data, username=reg_form.username.data,
                        password=reg_form.password.data)
        db.session.add(user)
        db.session.commit()

        flash('You have successfully registered', 'success')
        return redirect(url_for("auth.login"))

    return base_render("sign_up.html", reg_form=reg_form)


@auth_bp.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("common.info"))

    form = LoginForm()

    if form.validate_on_submit():
        db_user = db.session.query(AuthUser).filter_by(email=form.login.data).first()

        if not db_user or not db_user.verify_password(password=form.password.data):
            form.login.errors.append("Login or password is incorrect")
            form.password.errors.append("Login or password is incorrect")
            flash("Login or password is incorrect", 'danger')
            return base_render("login.html", form=form)

        login_user(db_user, remember=form.remember.data)

        flash("You have successfully signed-in", "success")
        return redirect(url_for("user.account"))

    return base_render("login.html", form=form)


@auth_bp.route("/logout")
@login_required
def logout():
    session.clear()
    logout_user()
    flash("You have successfully quit", "success")
    return redirect(url_for("auth.login"))


@auth_bp.route("/change_password", methods=["POST"])
@login_required
def change_password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        db_user = db.session.query(AuthUser).filter_by(email=current_user.email).first()

        if db_user and db_user.verify_password(form.old_password.data):
            db_user.password = form.new_password.data
            db.session.add(db_user)
            db.session.commit()
        else:
            flash("You have successfully changed your password", "success")
            form.old_password.errors.append("Enter the correct old password")

    return base_render("info.html", change_password_from=form, cookies=request.cookies.items())

lab4/Khalabarchuk_Project/app/authentication/templates/authentication/all-users.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('auth.static', filename='css/all-users.css') }}">
{% endblock %}

{% block content %}

    <div class="main-wrapper bg-white-gradient">
        <main class="main">
            <h3>All users</h3>
            <div class="table-wrapper bg-white-gradient-revers">
                <table class="table table-hover" style="--bs-table-bg:transparent;">
                    <thead>
                    <tr>
                        <th scope="col">email</th>
                        <th scope="col">username</th>
                        <th scope="col">avatar_image</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                        <tr>
                            <td>{{ user.email }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.avatar_image }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </main>
    </div>

{% endblock %}

lab4/Khalabarchuk_Project/app/authentication/templates/authentication/login.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('auth.static', filename='css/login.css') }}">
{% endblock %}

{% block content %}
    {% from "render-filed.html" import render_field %}

    <div class="main-wrapper">
        <main class="main">
            <form action="{{ url_for("auth.login") }}" method="post" class="login-form" novalidate>
                {{ form.csrf_token }}
                <div class="form-header">
                    <p class="form-title">
                        Login here🎯
                    </p>
                </div>
                <div> {{ render_field(form.login) }} </div>
                <div> {{ render_field(form.password) }} </div>
                <div class="checkbox"> {{ render_field(form.remember) }} </div>
                <div class="d-flex justify-content-center align-items-center"> {{ form.submit(class="default-submit") }} </div>
            </form>
        </main>
    </div>

{% endblock %}

lab4/Khalabarchuk_Project/app/authentication/templates/authentication/sign_up.html
{% extends 'portfolio-base.html' %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('auth.static', filename='css/login.css') }}">
{% endblock %}

{% block content %}
    {% from "render-filed.html" import render_field %}

    <div class="main-wrapper">
        <main class="main w-25">
            <form action="{{ url_for("auth.sign_up") }}" method="post" class="login-form w-100" novalidate>
                {{ reg_form.csrf_token }}
                <div class="form-header">
                    <p class="form-title">
                        Sign-up here🎉
                    </p>
                </div>
                <div> {{ render_field(reg_form.username) }} </div>
                <div> {{ render_field(reg_form.email) }} </div>
                <div> {{ render_field(reg_form.password) }} </div>
                <div> {{ render_field(reg_form.confirm_password) }} </div>
                <div class="d-flex justify-content-center align-items-center"> {{ reg_form.submit(class="default-submit") }} </div>
            </form>
        </main>
    </div>

{% endblock %}